version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - carbon-credits-network
      
networks:
  carbon-credits-network:
    external: true